baseURL: https://stefantobler.com
languageCode: en-us
title: Stefan Tobler
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-158607018-1

# Enable Disqus forum
disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # copyright
  copyright: © 2020 Copyright.

  # background image of the landing page
  background: "images/background.jpg"

  # GitHub repo URL of your site
  gitRepo: https://github.com/StefanTobler/stefantobler.github.io

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  customMenus:
  # - name: Notes
  #   url: https://hossainnotes.netlify.app/docs/example/

  # some information about you
  author:
    name: "Stefan Tobler"
    nickname: "Stefan"
    image: "images/avatar.jpg"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "stefan.tobler@uga.edu"
    # a summary of what you do
    summary:
    - I am a student
    - I am a hacker
    - I thrive to learn
